### ISSUE TITLE
Multi prop conditions

### ISSUE THREAD

**Issue by kasperpihl** [swipesapp/react-swiss#16]
Currently only one condition is supported.

Was thinking adding support for syntax like this:
```
const styles = {
  'theme!=red || active': {
    
  },
  'theme=blue && active': {
  
  }
  '(theme=red && active) || (theme=blue && !active)': {
    
  }
}
```

What do you think @thinklinux @iremlopsum

**Comment by thinklinux** [comment]
I like it! It's pretty standard and easy to remember syntax.

**Comment by kasperpihl** [comment]
Nice I will need your help on parsing the conditions with some regexes. :)
