### ISSUE TITLE
Warn when a Swiss rule is not referenced anywhere [enhancement]

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#19]
I think one of the biggest culprits to CSS bloat is that we don't know if a rule can be safely deleted. But if everything's JS object keys, then I imagine this'll be pretty easy.

I can even try to add it if @kasperpihl points me to the right files.

**Comment by kasperpihl** [comment]
Interesting, so the only thing we can check is whether the root level can be deleted.
```
export default styleSheet('App', {
  Wrapper: {
    // we can tell if this has been read somewhere
    active: {
      // cannot tell
    },
    'theme=red': {
      // cannot tell
    },
    '&:hover': {
      // cannot tell
    },
  }
})
```
so if no calls to styles.Wrapper is made, the whole Wrapper section be deleted. 
But subrules is impossible to tell as they depend on run-time conditions.
Ohh, and btw this is only possible if you use the styleSheet for all the styles.
```
styleElement('div', { ...style props }) // inline won't work.
```
Here is where I manipulate the styles object to have a secret __swissStyleClassName property so I can tell what className it should have on runtime.
https://github.com/swipesapp/react-swiss/blob/master/src/helpers/styleSheet.js#L22

And here is where we pick it up to determine the classNames.
https://github.com/swipesapp/react-swiss/blob/master/src/helpers/styleElement.js#L39

An easy fix would be to use the __swissStyleClassName as a getter instead, and keep track internally which gets called and which does not. 

Then once upon runtime, I'm thinking here:
https://github.com/swipesapp/react-swiss/blob/master/src/classes/SwissController.js#L14
Which is called runtime when components gets run, we can search for all objects in the styleSheets that has not yet been picked up.

A warning could look like this fx:
```
console.warn(`swiss styleSheet key 'Wrapper' never used in 'App'-stylesheet`);
```

Is this good enough or what were you thinking? :)

**Comment by atav32** [comment]
Yup, sounds great
