### ISSUE TITLE
How do I include an arbitrary CSS selector?

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#21]
The Calendly widget has its own DOM elements and classnames in an iframe. I'd like to write a Swiss rule that targets one of those elements, even though it's not create from the React app.

**Comment by kasperpihl** [comment]
2 ways

Option 1: use global styles. This should be in something like src/swiss/global-styles/calendly.js fx.
remember to import it in swiss/init.js
```
import { addGlobalStyles } from 'react-swiss'

addGlobalStyles({
  '.calendly-widget': {
    // add your styles here. (you can use mixins, variables and css selectors, but not props stuff....
  }
})
```

Option 2: use a parent react wrapper to style it
```
import { styleElement } from 'react-swiss';

const styles = {
  Wrapper: {
    // all wrapper stuff
    '& .calendly-widget': {
      // here add styles for the calendly styles
    }
  }
} 

render(
  <Wrapper>
     <iframe {...calendly} />
  </Wrapper>
)
```
