### ISSUE TITLE
Warn when type of styleElement is not defined. 

### ISSUE THREAD

**Issue by PepoDyakov** [swipesapp/react-swiss#22]
Add a warning whenever a styleElement is not defined. 

To reproduce the issue: just include:
`styleElement(' ')`

**Comment by thinklinux** [comment]
So you mean when you leave the first argument empty, right?

**Comment by PepoDyakov** [comment]
Yes, whenever the first argument is not set Swiss should create a warning that the styleElement is not defined, in order to give better visibility for debugging.

**Comment by kasperpihl** [comment]
@PepoDyakov I fixed this in https://github.com/swipesapp/react-swiss/commit/1150b33825a872a5bf5128fc64e4ddceb74fe67f

**Comment by PepoDyakov** [comment]
Great, thank you!
