### ISSUE TITLE
Warning: Received `false` for non-boolean attribute `visible`

### ISSUE THREAD

**Issue by thinklinux** [swipesapp/react-swiss#23]
That's a common warning these days. A lot of libraries are fixing it for themselves. I think react should decide on some approach and fix it but for now they are not. So maybe a temp fix will be good and then we can remove it.

![screen shot 2018-05-21 at 11 03 58](https://user-images.githubusercontent.com/326949/40297098-45d1c568-5ce7-11e8-813f-7f6f6ad56ca2.png)

The fix probably should be applied do [this file](https://github.com/swipesapp/react-swiss/blob/ca56b2f205c2ca6350a212e44d81db68dccce537/src/components/SwissElement.js)

It's about stringifying boolean or even better, apply the attribute for true and omit it for false.

P.S. You can reproduce the warning if you run the our website :))

**Comment by iremlopsum** [comment]
That warning probably happens because you're passing a prop to a Swiss element, but not defining that prop in swiss styles.

The way how it works is that all props that are defined in styles are stripped before render.

**Comment by thinklinux** [comment]
Okay, Kris, what about that?

![screen shot 2018-05-21 at 17 50 55](https://user-images.githubusercontent.com/326949/40313901-8feb0956-5d1f-11e8-8ab3-a5ca03f7245d.png)

showModal is declared in swiss styles but I'm still getting a warning for this property:

![screen shot 2018-05-21 at 17 52 53](https://user-images.githubusercontent.com/326949/40314011-dfeb7792-5d1f-11e8-89a2-a0f7d32579d2.png)

showModal is still trying to get to the DOM for some reason.

**Comment by iremlopsum** [comment]
That's because you have openModal declared and not showModal. Tisho tisho tisho tisho

**Comment by iremlopsum** [comment]
showModal is a prop within a prop, that should not work

**Comment by thinklinux** [comment]
You wrote this. Kris kris kris kris

![screen shot 2018-05-21 at 18 18 38](https://user-images.githubusercontent.com/326949/40315228-7528693e-5d23-11e8-81a0-6b32c38a73ca.png)

**Comment by kasperpihl** [comment]
If you 2 kids could just get along, I'll look into this. :)

**Comment by kasperpihl** [comment]
I fixed this. If you still see this warning in 0.2.22 please let me know.

**Comment by thinklinux** [comment]
Awesome, thanks!
