### ISSUE TITLE
How do I add an ID to an element?

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#24]
Tried

```
<Element id="elementId" />
```

but it doesn't seem to set the `id` attribute in the rendered DOM element.

Nor does it seem to pass it along as a prop.

**Comment by kasperpihl** [comment]
API is as you tried out: 
![screen shot 2018-05-24 at 09 18 57](https://user-images.githubusercontent.com/1443231/40470385-a9cbff72-5f33-11e8-90f4-8545eeb7ef94.png)

Can you show me the styleElement code? Are you trying to wrap another component?

**Comment by atav32** [comment]
Huh, I'll try it again haha. Maybe I didn't wait long enough to refresh.

**Comment by kasperpihl** [comment]
I'm closing for now. Reopen if you find something unexpected. 👍
