### ISSUE TITLE
Unexpected behavior of &

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#25]
Take the example of,

``` Javascript
Wrapper: {

  '&:nth-child(odd)': {
    '& > div': {
      background: 'green',
    },
  },

  '&:nth-child(even)': {
    '& > div': {
      background: 'yellow',
    },
  },
},
```

Being used to how SCSS works, I would expect the 1st, 3rd and 5th element to have a child element with a green background. Instead, all of the child elements have yellow backgrounds.

I suppose if I think about it, `&` refers to the named selector, not the selector that is nesting it. But it was unexpected.

**Comment by kasperpihl** [comment]
swiss-react 0.2.26 acts as you'd expect.

It even support:
```
'&:nth-child(even), &:nth-child(odd)': {
  '& > div, & > span': {
    background: 'yellow',
  },
},
```

Edited:
Awesome catch btw!!! :)

**Comment by iremlopsum** [comment]
I might be wrong, but I don't think that's what @atav32 meant by this. The ampersand works differently in swiss and sass.

If we take the example code of

```
Wrapper: {

  '&:nth-child(odd)': {
    '& > div': {
      background: 'green',
    },
  },

  '&:nth-child(even)': {
    '& > div': {
      background: 'yellow',
    },
  },
},
```

then in sass this compiles to

```
.wrapper:nth-child(odd) > div {
  background: green;
}
.wrapper:nth-child(even) > div {
  background: yellow;
}
```

but in swiss it should compile to

```
.wrapper > div {
  background: green;
}

 .wrapper > div {
  background: yellow;
}
```

The reason is that ampersand in swiss targets the root of the element, which is `Wrapper` in this case. And swiss will not respect nesting here. In Sass it always targets the parent selector, which in this case would be `.wrapper:nth-child(odd) || .wrapper:nth-child(even)`.


This is an inherit difference in swiss

**Comment by iremlopsum** [comment]
This kind of nesting is considered an anti-pattern in sass though. So I don't see it as a problem if swiss doesn't support it.

**Comment by kasperpihl** [comment]
@iremlopsum I already made an update supporting this.
```
  Wrapper: {
    '&:nth-child(odd)': {
      '& > div': {
        background: 'green',
      },
    },

    '&:nth-child(even), &:nth-child(odd)': {
      '& > div, & > span': {
        background: 'yellow',
      },
    },
  },
```
Now turns into:
```
.Wrapper-0:nth-child(odd) > div {
  background: green;
}
.Wrapper-0:nth-child(even) > div, .Wrapper-0:nth-child(odd) > div, .Wrapper-0:nth-child(even) > span, .Wrapper-0:nth-child(odd) > span {
  background: yellow;
}

```

Normal prop conditions etc still work as expected. 

Should I revert this you think?

**Comment by iremlopsum** [comment]
@kasperpihl this is a pretty big breaking change. I think that actually using the ampersand the same way as Sass and Less does it makes sense, as it will behave in an expected way.

Let's keep it for now. Hopefully won't have too many issues when updating projects.

**Comment by kasperpihl** [comment]
Yeah I like having it like sass as well. Just makes it more intuitive, I can add a warning easily in a version, that identifies all the places this change happens, then we can check the projects as we update them.

**Comment by atav32** [comment]
Yeah I think it'll help adoption if it works like SCSS.
