### ISSUE TITLE
Swiss performance bottleneck

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#27]
I noticed that loading a React App that uses Swiss takes a surprising amount of time. It appears that `styleElement()` is causing React's render cycle to thrash.

<img width="1377" alt="screen shot 2018-09-25 at 2 27 48 pm" src="https://user-images.githubusercontent.com/622185/46045065-62051c00-c0d1-11e8-8619-2baed2a142db.png">

Each of these purple chunks is an expensive animation. 

<img width="3008" alt="screen shot 2018-09-25 at 2 50 30 pm" src="https://user-images.githubusercontent.com/622185/46045736-5fa3c180-c0d3-11e8-87ec-18335c763db9.png">

<img width="3005" alt="screen shot 2018-09-25 at 2 53 35 pm" src="https://user-images.githubusercontent.com/622185/46045745-692d2980-c0d3-11e8-966e-bcfeda268e4c.png">

Profiling other React apps, I noticed that React is usually really good about batching it's animation calculations. But somehow Swiss gets in its way. Probably with the bulk CSS class changes.

**Comment by atav32** [comment]
There's also some weird interaction between React DOM hydration and Swiss, but I haven't dug enough to understand it. `styleElement()` seems to cause the hydration to be called over and over again.

<img width="590" alt="screen shot 2018-09-25 at 3 05 06 pm" src="https://user-images.githubusercontent.com/622185/46046028-6c74e500-c0d4-11e8-9575-44b1f7d43622.png">

**Comment by atav32** [comment]
There's also a corner-case where if a component using Swiss is re-rendered (say a countdown timer), the `<style id="sw-newglobal" type="text/css">` tag is reinjected each time.

**Comment by kasperpihl** [comment]
Awesome finds Brian, I'll give this a refactor in the coming weeks when I get time.

I have a strategy to try use ReactDOM.render to keep the styles up to date, right now I do this manually with updating a dom element.
Will probably need you to help trying it out again on the edge cases you found

**Comment by atav32** [comment]
Just digging into this more, it seems like `printToCss()` (and possibly `replacePropsAndVarForSelectors()`) are the main culprits.

I'm not too sure the use case of the function, but a regex inside a recursive function seems like a red flag 🚩 

Is there a way to simplify what this is doing?

I'm happy to make the change if you can walk me through it.

**Comment by kasperpihl** [comment]
We should grab a call and go over some of this together. 
ReplacePropsAndVarForSelector adds support for using props and variables in the selector statement

`”@media $min400”: {...}` fx

printToCss converts our JS styles object into CSS so it can be added to the dom. We need both of these, so I guess the question is if we can do it more optimized either with better code or some caching mechanism.

Again happy to grab a call. Just write me on iMessage

**Comment by kasperpihl** [comment]
Just released v0.4.2 and now the cpu footprint should be absolutely minimal
- Now it's caching generated styles based on the unique props used to make them
- It's supporting hydration from server-side rendering so that when you hydrate the app, it gets the cache from the server and doesn't recalculate things again.

Can't wait to see the gains on the bytegain website.

**Comment by kasperpihl** [comment]
One thing that could be improved though, is the conversion of the style object to the iteratable array, basically the recursive function convertStylesToArray called in styleSheet.js.
That conversion could either happen as a babel plugin, or we could "lazy"-convert it so only if styles are about to get calculated

**Comment by atav32** [comment]
Awesome, can't wait to try it!

**Comment by atav32** [comment]
Looks like the performance optimizations worked beautifully!

<img width="1680" alt="screen shot 2019-01-01 at 2 52 33 pm" src="https://user-images.githubusercontent.com/622185/50575929-3e8af500-0dd5-11e9-9d87-efefecefaea5.png">

**Comment by atav32** [comment]
Here's a breakdown of the events, https://docs.google.com/spreadsheets/d/14no-UuSKJOHDeBuahcpjMfPqM81vxe4bj5K9xLhpx8M/edit?usp=sharing

The main gains are during the 2nd and 3rd "recalculate styles" cycles. Those were the large purple chunks in the old screenshots. Each used to take `~1000ms` and block the main rendering thread.

Now the 2nd recalculate takes `15ms`. The 3rd takes less than `5ms`. Huge improvements.
