### ISSUE TITLE
Using prop with _el mixin does not work

### ISSUE THREAD

**Issue by thinklinux** [swipesapp/react-swiss#30]
If `large` is set the element is still `h2`.

```js
_el: 'h2',
large: {
  _el: 'h1',
}
```

**Comment by PepoDyakov** [comment]
Did that ever work at any point? Because I've tried it as well some time ago and it didn't work for me.

**Comment by thinklinux** [comment]
I don't think it ever worked. I don't know if it can work :) I just tried it out because of the syntax it looks that I should be able to do it.
