### ISSUE TITLE
Nested props does not get removed from the DOM

### ISSUE THREAD

**Issue by thinklinux** [swipesapp/react-swiss#31]
My styles

```js
  FormButton: {
    _el: 'button',
    top: 0,
    right: 0,
    padding: 0,
    cursor: 'pointer',
    outline: 'none',
    width: '110px',
    border: 'none',
    height: '100%',
    color: '$deepBlue100',
    fontSize: '15px',
    position: 'absolute',
    backgroundColor: 'white',
    transition: 'color 500ms',

    '&:hover': {
      color: '$blue100',
    },

    openModal: {
      '@media $min1000': {
        display: 'none',
      },

      '@media $max1000': {
        top: 'calc(50% - 20px)',
        right: '5%',
        height: '40px',
        color: '$blue100',
        zIndex: 3,
        boxShadow: '0 3px 6px 0 rgba($deepBlue50, .5)',
        borderRadius: '3px',
      },

      showModal: {
        display: 'none',
      },
    },
  },
```

`showModal` is not removed from swiss and gets pushed to react => react complains because it is not a valid DOM property

![screenshot 2019-01-08 at 10 13 15](https://user-images.githubusercontent.com/326949/50817895-05e7a000-132e-11e9-9118-a7fd4ea32575.png)

**Comment by PepoDyakov** [comment]
In which file are these styles applied? I want to take a look. 

I run in this error quite often as well and the problem is usually lying in the component itself because I've not removed the prop itself.

**Comment by thinklinux** [comment]
https://github.com/swipesapp/swipes-website/blob/master/src/client/components/subscribe-form/SubscribeForm.swiss.js#L235

**Comment by kasperpihl** [comment]
This is expected behaviour.
We need a default mixin called: _excludeProps: ['showModal']
And one called _forwardProps: ['showModal'] to force forward it.
