### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by kasperpihl** [swipesapp/react-swiss#5]
Showcase swiss and what you can do with it. The world deserves it!

Pages
- [ ] Home page
- [x] Getting started
- [ ] How it works
- [x] Props
- [ ] Props advanced
- [x] Mixins
- [x] Variables
- [ ] Plugins
- [ ] Global Styles
- [x] React Native
- [x] Server Side Rendering
- [x] CSS: Targeting/selectors
- [ ] CSS: Media queries
- [ ] CSS: Animations
- [x] CSS: Prefixing
- [ ] Best practices

**Comment by atav32** [comment]
Can I get a preview? Even if it's unfinished 😂

**Comment by kasperpihl** [comment]
http://swiss-react.com
Main ones that is written so far:
that should give you a good idea
/props
/variables
/mixins
/css-selectors

**Comment by kasperpihl** [comment]
Sorry, it's swiss-react.com

**Comment by kasperpihl** [comment]
Main ones that is written so far:
that should give you a good idea
/props
/variables
/mixins
/css-selectors

**Comment by atav32** [comment]
High-level question: what're the advantages of Swiss over the other CSS-in-JS libraries? https://github.com/MicheleBertoli/css-in-js#features

**Comment by kasperpihl** [comment]
It's all about ease of use and syntax.
- Built for a component world, not the css way of thinking. This means better code organisation.
- Components with dynamic styles that's easy to target. -> http://swiss-react.com/docs/props
- Reusable variables/mixins with a simple syntax that does not need imports a million places.
http://swiss-react.com/docs/mixins
http://swiss-react.com/docs/variables
Happy to give you a walkthrough of the value once I'm back monday.
